import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';
export default defineConfig({
  redirects: {
    '/about-us': '/about/',
    '/contact-us': '/contact/',
    '/service': '/services/',
    '/services/nlp-executive-business-life-coaching': '/services/nlp-executive-coaching/',
    '/our-team': '/about/',
    '/pricing': '/contact/',
    '/faq': '/#faq',
    '/terms-conditions': '/privacy-policy/',
    '/privacy-policy-2': '/privacy-policy/',
    '/blog': '/',
    '/portfolio': '/',
    '/hello-world': '/',
    '/why-financial-forecasting-is-key-to-your-business-success': '/',
    '/how-to-optimize-your-business-budget-for-maximum-profitability': '/',
    '/10-common-financial-mistakes-small-businesses-make-and-how-to-avoid-them': '/',
    '/understanding-the-basics-of-investment-management': '/',
    '/top-10-tips-for-effective-financial-planning': '/',
    '/how-to-prepare-for-tax-season-a-comprehensive-guide': '/',
    '/the-importance-of-estate-planning-protecting-your-legacy': '/',
    '/managing-debt-strategies-for-financial-freedom': '/',
    '/the-role-of-financial-advisors-how-they-can-help-you': '/',
    '/insights-from-top-business-consultancy-experts': '/',
  },
  site: 'https://khulabusinesssolutions.co.za',
  trailingSlash: 'always',
  integrations: [sitemap({ filter: (p) => !p.includes('thank-you') && !p.includes('corporate-training-south-africa') })],
});
